### ISSUE TITLE
消息点击后的url，现在可以动态设置吗

### ISSUE THREAD

**Issue by koyuhau** [brucx/mp-push-leancloud#18]
现在我这边想实现功能：消息点击后，希望能跳到一个跟消息相关的页面进行详细显示。
请问这套代码现在可以实现吗？

**Comment by brucx** [comment]
https://github.com/brucx/mp-push-leancloud/blob/71db2eb2fd34806b9efa3a01afeb3fe7f6dfda8e/utils.js#L22

接口文档 
http://doxmate.cool/node-webot/wechat-api/api.html#api_template_exports_sendTemplate

另外建议使用https://github.com/brucx/mp-push-nestjs
